[package]
name = "rcrypt"
version = "0.1.0"
authors = ["blit32 <blit32@circuitsofimagination.com>"]

[dependencies]
rust-crypto = "0.2.36"
rustc-serialize = "0.3"

[[bin]]
name = "rhash"
path = "src/rhash.rs"
